### ISSUE TITLE
Support for C++20 modules extensions

### ISSUE THREAD

**Issue by MattBolitho** [cadamsdev/vscode-jetbrains-icon-theme#123]
C++20 introduced a new way to build code with [modules](https://en.cppreference.com/w/cpp/language/modules).

Whilst there isn't total consensus on the extension to use for these files yet, `.cxxm`, `.cppm`, `.ixx`, `.ccm`, and `.c++m` have emerged as some fairly common extensions that are also registered in CLion 2023 by default:
![image](https://github.com/user-attachments/assets/7f49139e-ea0c-4887-a803-9ecc43578cad)

Would it be possible to also add these file extension associations to this VS Code extension?

As an aside: thank you very much for this extension - it's great! 😊

**Comment by cadamsdev** [comment]
Yeah, I don't mind. Feel free to create a PR.

Looks like you're using the v1 icon set, so you would just update this
https://github.com/cadamsdev/vscode-jetbrains-icon-theme/blob/main/assets/v1/theme-dark.json#L278
add
```json
    "cpp": "file_type_cpp",
    "cxxm": "file_type_cpp",
    "cppm": "file_type_cpp",
    "ixx": "file_type_cpp",
```
etc

**Comment by MattBolitho** [comment]
Great thanks! I'll try to get around to that soon.

> Looks like you're using the v1 icon set

My screenshot was from CLion and unfortunately I only have access to 2023.1 which uses the old icons. I'd like to update both sets of icons if that's OK?

**Comment by cadamsdev** [comment]
> My screenshot was from CLion and unfortunately I only have access to 2023.1 which uses the old icons. I'd like to update both sets of icons if that's OK?

Yeah that's fine.

EDIT:
Your changes should be in [v2.21.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.21.0)
