### ISSUE TITLE
Add protobuf icon.

### ISSUE THREAD

**Issue by blackcater** [cadamsdev/vscode-jetbrains-icon-theme#129]
![protoFile](https://github.com/user-attachments/assets/152beaef-bdf3-4a0b-821d-8c4c6d5e1cf1)
![protoFile@2x](https://github.com/user-attachments/assets/9de4a8ef-2793-4676-aeb6-834a2187aaa0)
![protoMessage](https://github.com/user-attachments/assets/4eaed62c-8e24-41c8-b713-b9d1e7a57bb7)
![protoMessage@2x](https://github.com/user-attachments/assets/c65b3b56-6716-4406-b71a-8b7f620be43e)

I found these files in `Intellij IDEA.app/Contents/protoeditor/lib/protoeditor.jar` package.

**Comment by cadamsdev** [comment]
Notes
Looks like IntelliJ has a Protobuf plugin that has these new icons
https://plugins.jetbrains.com/plugin/14004-protocol-buffers

Icons
https://intellij-icons.jetbrains.design/#ProtoeditorCoreIcons-icons-newui-protoFile

Protobuf icon light
![light](https://intellij-icons.jetbrains.design/icons/ProtoeditorCoreIcons/icons/newui/protoFile.svg)

Protobuf icon dark
![dark](https://intellij-icons.jetbrains.design/icons/ProtoeditorCoreIcons/icons/newui/protoFile_dark.svg)

**Comment by cadamsdev** [comment]
Added
https://github.com/cadamsdev/vscode-jetbrains-icon-theme/pull/130
