### ISSUE TITLE
New go.mod go.sum go.work file icon

### ISSUE THREAD

**Issue by blackcater** [cadamsdev/vscode-jetbrains-icon-theme#131]

**Comment by cadamsdev** [comment]
Here's what Golang uses for these icons
<img width="378" alt="image" src="https://github.com/user-attachments/assets/e7a15dd2-072a-4a76-98ac-ea64d7e4619c">

**Comment by cadamsdev** [comment]
Added
https://github.com/cadamsdev/vscode-jetbrains-icon-theme/pull/132
