### ISSUE TITLE
Add icon for Elixir

### ISSUE THREAD

**Issue by thiagomajesk** [cadamsdev/vscode-jetbrains-icon-theme#24]
Hi! I was using another Jetbrains icon library and also have made the same request over there without much success. Could you add support for elixir files? Here is the issue I had opened in the other repository with more details: https://github.com/marlongerson/jetbrains-icons/issues/2.

**Comment by chadalen** [comment]
Hi. How about icon from here?
[https://github.com/KronicDeth/intellij-elixir/blob/main/resources/icons/language/elixir.svg](https://github.com/KronicDeth/intellij-elixir/blob/main/resources/icons/language/elixir.svg)

For file types
`.ex`, `.exs`, `.html.eex`, `.html.leex`
![https://github.com/KronicDeth/intellij-elixir/blob/main/resources/icons/language/elixir.svg](https://github.com/KronicDeth/intellij-elixir/blob/main/resources/icons/language/elixir.svg)

**Comment by thiagomajesk** [comment]
Hi @chadalen, thanks for the response! I was looking at the official icon list from the Jetbrains website and found a pattern that we can use: https://jetbrains.design/intellij/resources/icons_list. For the `.ex` and `.exs` extensions, you can use the 'ruby_file' as a template by replacing the language icon (you'll probably have to use a different purple to increase contrast, I suggest using the same tone as the 'sequence' icon). For the `.html.eex`, `.html.leex` and `.html.heex` I'd just use the 'rhtml' icon but with the extension name `eex`, `leex` and `heex` instead of the letter 'R'.

**Comment by cadamsdev** [comment]
Elixir icons have been added to the new 2023+ theme
https://github.com/cadamsdev/vscode-jetbrains-icon-theme/pull/110
