### ISSUE TITLE
Add icon for slim

### ISSUE THREAD

**Issue by cadamsdev** [cadamsdev/vscode-jetbrains-icon-theme#36]
http://slim-lang.com/

Icon
![slim](https://user-images.githubusercontent.com/12568665/168404481-daea408d-abf1-4341-a484-e7afecc844ad.svg)

**Comment by OlegChuev** [comment]
Can be closed since it was added here: 
https://github.com/cadamsdev/vscode-jetbrains-icon-theme/pull/99/files

**Comment by cadamsdev** [comment]
Closing issue since the v1 icon set is deprecated.
