### ISSUE TITLE
Add file icon for .pcss

### ISSUE THREAD

**Issue by cadamsdev** [cadamsdev/vscode-jetbrains-icon-theme#41]
This is for [PostCSS](https://postcss.org/)

Files ending with
.pcss

File names
postcss.config.js
postcss.config.ts

icon
![postcss](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/12568665/5db3f780-e70c-4f98-9377-e42a2f0b2ecb)

COA:
- Icon should be added to the 2023+ theme (both light and dark)

**Comment by OlegChuev** [comment]
Not actual since it was added here: https://github.com/cadamsdev/vscode-jetbrains-icon-theme/pull/84
