### ISSUE TITLE
html.erb icon

### ISSUE THREAD

**Issue by gagegolden00** [cadamsdev/vscode-jetbrains-icon-theme#48]
Need a better icon for html.erb files

**Comment by cadamsdev** [comment]
Feel free to suggest an icon.

Looks like intellij-icons has this we can use
https://[intellij-icons.jetbrains.design/icons/RubyIcons/icons/erb/erbFile.svg](https://intellij-icons.jetbrains.design/icons/RubyIcons/icons/erb/erbFile.svg)

![erbFile](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/12568665/3eabfc34-a314-48a7-884d-c1819e0f526f)

**Comment by cadamsdev** [comment]
Added in [v1.1.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v1.1.0)
