### ISSUE TITLE
Icons V2 - Certain file types are not represented by the correct icon

### ISSUE THREAD

**Issue by oresttokovenko** [cadamsdev/vscode-jetbrains-icon-theme#62]
<img width="300" alt="Screenshot 2023-07-06 at 13 55 12" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/51058259/f64033ee-5871-4414-bced-148109fa4b63">

Files types like TOML, Python, terraform, etc use the default 'file extension not found' icon instead of the corresponding Jetbrains icon.

**Comment by cadamsdev** [comment]
Fixed, added in v2.2.0
