### ISSUE TITLE
Icons V2 - Certain file types are not represented by the correct icon pt. 2

### ISSUE THREAD

**Issue by oresttokovenko** [cadamsdev/vscode-jetbrains-icon-theme#66]
<img width="318" alt="Screenshot 2023-07-08 at 10 28 06" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/51058259/a57951fa-cb28-49a5-a1c7-805697a79b5d">

Thank you for the previous update! There are a few more icons that aren't working:
* .cfg
* Makefile
* .pdf
* .tex
* .cls

**Comment by cadamsdev** [comment]
I can add them I just need to know which icons these use.

**Comment by oresttokovenko** [comment]
I'm not able to link the individual files but here is the image and the name

Makefile: 

<img width="461" alt="Screenshot 2023-07-08 at 22 54 53" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/51058259/c864801e-b0d1-40f8-b2c5-c653609c39ed">

.cfg

<img width="162" alt="Screenshot 2023-07-08 at 22 56 52" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/51058259/f42851fc-ce92-4e5b-9fd4-cde0bd95c3f5">

Seems Jetbrains doesn't have a .tex , css or .pdf filetype icon

**Comment by cadamsdev** [comment]
Added Makefile, .cfg, and .env in [v2.3.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.3.0).

Will add .tex and .pdf when there's an icon we can use for those.
