### ISSUE TITLE
[Icon Request] Add Icon for Svelete

### ISSUE THREAD

**Issue by baptistejouin** [cadamsdev/vscode-jetbrains-icon-theme#69]
## It seems there's no support for Svelte files

With "JetBrain Icon Theme 2023+ UI Dark"
<img width="278" alt="image" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/92529084/edde5704-7013-4cff-afb4-2c9ebcd53981">

With "JetBrain Icon Theme v1"
<img width="283" alt="image" src="https://github.com/cadamsdev/vscode-jetbrains-icon-theme/assets/92529084/48b2f306-00c9-47d9-81f1-e8e8469145ee">

## Utilities
- https://svelte.dev/
- https://github.com/sveltejs/branding

**Comment by cadamsdev** [comment]
Hey, thanks for reporting the issue. This should be in [v2.4.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.4.0)
