### ISSUE TITLE
Add icons for Rust language files

### ISSUE THREAD

**Issue by olivier-fs** [cadamsdev/vscode-jetbrains-icon-theme#72]
Hi! Very nice theme.
The only thing that stops me from using it is the lack of icons for the Rust language :
- *.rs (source files)
- Cargo.toml, Cargo.lock (package manager files)

I knon that Rust isn't as popular as say JS or C++ but it's gaining a lot of traction and I love it !
TIA

**Comment by cadamsdev** [comment]
Hey thanks for reporting the issue!

Added in [v2.5.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.5.0)

**Comment by olivier-fs** [comment]
Hi
Nice ! I'm switching from (also great) Bromium to JetBrains now :-)
Thank you

**Comment by olivier-fs** [comment]
Another small rust-related issue.

Rust's 'cargo' build tool looks not only for Cargo.toml file (that now has proper icon) but also for 'rust-toolchain.toml' where one can specify e.g. nightly toolchain instead of stable.

'rust-toolchain.toml' files have a blue T (toml) icon.
Would be much better to assign these the same icon as Cargo.toml as it's also related to the build tools.

[ Still greatly enjoying this theme BTW :-)) Be it rust or c++ it looks fantastic, even more with dark/black themes ]

**Comment by cadamsdev** [comment]
@olivier-fs Fixed in [v2.6.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.6.0)
