### ISSUE TITLE
Add support for CMake

### ISSUE THREAD

**Issue by olivier-fs** [cadamsdev/vscode-jetbrains-icon-theme#73]
Hi!
I use CMake for almost all C/C++ projects, and CMake files/directories have no icons
- 'CMakeLists.txt' makefile
- CMake build directories (most often a 'build' subdirectory, but actually any directory with a 'CMakeCache.txt' file and a '.cmake' subdirectory)

That would be a nice addition to this beautiful theme.
TIA

**Comment by cadamsdev** [comment]
Added in [v2.5.0](https://github.com/cadamsdev/vscode-jetbrains-icon-theme/releases/tag/v2.5.0)

**Comment by olivier-fs** [comment]
Thanks! Much easier to spot those CMakeFiles.txt now.
